"""empty message

Revision ID: 2557dd1ebcd8
Revises: cb882321a76b
Create Date: 2020-04-11 15:21:00.867373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2557dd1ebcd8'
down_revision = 'cb882321a76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scraped_data_created_on', table_name='scraped_data')
    op.drop_index('ix_scraped_data_link', table_name='scraped_data')
    op.drop_index('ix_scraped_data_name', table_name='scraped_data')
    op.drop_table('scraped_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.VARCHAR(), nullable=True),
    sa.Column('rating', sa.VARCHAR(), nullable=True),
    sa.Column('photo', sa.VARCHAR(), nullable=True),
    sa.Column('total_reviews', sa.VARCHAR(), nullable=True),
    sa.Column('total_rating', sa.VARCHAR(), nullable=True),
    sa.Column('link', sa.VARCHAR(), nullable=True),
    sa.Column('query', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scraped_data_name', 'scraped_data', ['name'], unique=1)
    op.create_index('ix_scraped_data_link', 'scraped_data', ['link'], unique=1)
    op.create_index('ix_scraped_data_created_on', 'scraped_data', ['created_on'], unique=False)
    # ### end Alembic commands ###
