"""empty message

Revision ID: 29f43a68bb76
Revises: 4d9d45464680
Create Date: 2020-04-13 16:30:49.250888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f43a68bb76'
down_revision = '4d9d45464680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scraped_data_link', table_name='scraped_data')
    op.drop_index('ix_scraped_data_name', table_name='scraped_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_scraped_data_name', 'scraped_data', ['name'], unique=False)
    op.create_index('ix_scraped_data_link', 'scraped_data', ['link'], unique=1)
    # ### end Alembic commands ###
