"""empty message

Revision ID: 46423082b801
Revises: 2557dd1ebcd8
Create Date: 2020-04-11 15:21:14.021610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46423082b801'
down_revision = '2557dd1ebcd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('total_reviews', sa.String(), nullable=True),
    sa.Column('total_rating', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_data_created_on'), 'scraped_data', ['created_on'], unique=False)
    op.create_index(op.f('ix_scraped_data_link'), 'scraped_data', ['link'], unique=True)
    op.create_index(op.f('ix_scraped_data_name'), 'scraped_data', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_data_name'), table_name='scraped_data')
    op.drop_index(op.f('ix_scraped_data_link'), table_name='scraped_data')
    op.drop_index(op.f('ix_scraped_data_created_on'), table_name='scraped_data')
    op.drop_table('scraped_data')
    # ### end Alembic commands ###
