"""empty message

Revision ID: 4cd97c0f838c
Revises: e82fb205239c
Create Date: 2020-04-11 15:08:35.150805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd97c0f838c'
down_revision = 'e82fb205239c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('total_reviews', sa.String(), nullable=True),
    sa.Column('total_rating', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_data_created_on'), 'scraped_data', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_data_created_on'), table_name='scraped_data')
    op.drop_table('scraped_data')
    # ### end Alembic commands ###
