"""empty message

Revision ID: 4d9d45464680
Revises: a7133f7ac483
Create Date: 2020-04-13 16:23:31.748021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9d45464680'
down_revision = 'a7133f7ac483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scraped_data_name', table_name='scraped_data')
    op.create_index(op.f('ix_scraped_data_name'), 'scraped_data', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_data_name'), table_name='scraped_data')
    op.create_index('ix_scraped_data_name', 'scraped_data', ['name'], unique=1)
    # ### end Alembic commands ###
