"""empty message

Revision ID: a7133f7ac483
Revises: 
Create Date: 2020-04-13 15:31:22.264541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7133f7ac483'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('total_reviews', sa.String(), nullable=True),
    sa.Column('total_rating', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_data_created_on'), 'scraped_data', ['created_on'], unique=False)
    op.create_index(op.f('ix_scraped_data_link'), 'scraped_data', ['link'], unique=True)
    op.create_index(op.f('ix_scraped_data_name'), 'scraped_data', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_on'), 'user', ['created_on'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_on'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_scraped_data_name'), table_name='scraped_data')
    op.drop_index(op.f('ix_scraped_data_link'), table_name='scraped_data')
    op.drop_index(op.f('ix_scraped_data_created_on'), table_name='scraped_data')
    op.drop_table('scraped_data')
    # ### end Alembic commands ###
