"""empty message

Revision ID: b0162ca17c50
Revises: 46423082b801
Create Date: 2020-04-11 15:33:30.126360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0162ca17c50'
down_revision = '46423082b801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_data', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_data', 'website')
    # ### end Alembic commands ###
